import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

const TRANSACTION_GUARD_MESSAGE =
  "Route handlers must open transactions through runAuthorizedTransaction/runIdempotent so authorization is re-checked against a fresh actor document at commit.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["sw/**/*.{js,mjs}"],
    languageOptions: {
      globals: {
        self: "readonly",
        caches: "readonly",
        fetch: "readonly",
        URL: "readonly",
        SW_VERSION: "readonly",
        PRECACHE_URLS: "readonly",
        STRATEGY: "readonly",
        selectStrategy: "readonly",
        cacheName: "readonly",
        isStaleCache: "readonly",
      },
    },
  },
  {
    files: ["src/app/api/**/*.ts"],
    ignores: ["src/app/api/auth/session/route.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/firebase-admin", "firebase-admin/firestore"],
              importNames: ["getAdminFirestore", "getAdminApp", "getFirestore"],
              message: TRANSACTION_GUARD_MESSAGE,
            },
          ],
        },
      ],
    },
  },
  // Turn off ESLint rules that conflict with Prettier formatting. Must come last.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Generated by scripts/build-sw.mjs from sw/.
    "public/sw.js",
  ]),
]);

export default eslintConfig;
