import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const swDir = join(root, "sw");
const publicDir = join(root, "public");

function collectPrecacheUrls() {
  const urls = ["/manifest.webmanifest", "/favicon.ico"];
  for (const file of readdirSync(join(publicDir, "icons")).sort()) {
    urls.push(`/icons/${file}`);
  }
  return urls;
}

export function inlineCore(source) {
  const core = source
    .replace(/^export\s+(?=(?:(?:async\s+)?function(?:\s*\*)?|class|const|let|var)\s+)/gm, "")
    .replace(/^export\s*\{[^}]*\};?\s*$/gm, "")
    .trim();

  if (/^\s*(?:import|export)\b/m.test(core)) {
    throw new Error("sw-core.mjs contains unsupported ESM syntax for a classic service worker");
  }

  return core;
}

export function buildServiceWorker() {
  const core = inlineCore(readFileSync(join(swDir, "sw-core.mjs"), "utf8"));
  const template = readFileSync(join(swDir, "sw.template.js"), "utf8").trim();
  const precacheUrls = collectPrecacheUrls();

  const version = createHash("sha256")
    .update(core)
    .update(template)
    .update(JSON.stringify(precacheUrls))
    .digest("hex")
    .slice(0, 10);

  const output = `// GENERATED by scripts/build-sw.mjs from sw/sw-core.mjs + sw/sw.template.js.
// Do not edit by hand. Regenerate with \`pnpm build:sw\` (runs during \`pnpm build\`).
const SW_VERSION = ${JSON.stringify(version)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls)};

${core}

${template}
`;

  writeFileSync(join(publicDir, "sw.js"), output);
  console.log(
    `build-sw: wrote public/sw.js (version ${version}, ${precacheUrls.length} precache urls)`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildServiceWorker();
}
